### ISSUE TITLE
pull event data based on group urlnames

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/meet-maynard#3]
## Problem

We need the event data in order to access the rsvps for issue #2 . 

## Solution
* pull event data https://www.meetup.com/meetup_api/docs/:urlname/events/#list using group ids
* store event id
* store group url or group id
* store watermark data for the given group url and event id

# Blocking
by #4 and #7

**Comment by littleforest** [comment]
@zassmin I don't know if the Go API call was really giving you what you want:

`https://api.meetup.com/%s/events?order=created&desc=1&status=past&page=%d` with `page=1` does indeed return a single record for an event at 2:00pm today, which is just the first record returned when this endpoint is called without any parameters.

**Comment by littleforest** [comment]
Well, to clarify -- I guess it would eventually get you what you want as you increase the `page` parameter... :)

Anyway, just passing `past` seems to get us what we want. So to clarify for this -- we only want to be collecting data for past events? So if I run this today, and then again next week, it's fine that it just returns past events up through the current time?

**Comment by littleforest** [comment]
Here is my suggestion for this:

1. Finish out the [pagination](https://github.com/WomenWhoCode/meet-maynard/issues/26) issue, allowing a passing of a date to prevent infinite pagination.
2. Write a rake task that first gets the time of the most recent event stored (or default to some lower bound), and then formulate the url using `scroll=since:2016-09-28T15:30:00.000-07:00` format, using the time of the last stored event as the parameter.  
3. Get further paginated results if they exist (likely not).

**Comment by zassmin** [comment]
@littleforest Looks great! 

This might be implied but just noting here: we are pulling the event data for https://github.com/WomenWhoCode/meet-maynard/issues/3#issuecomment-308260260 for each group urlname sorted in our db
