### ISSUE TITLE
add watermark

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/meet-maynard#4]
# Problem

We want to pull past data, and we don't want to pull data we already have. 

# Solution
- incorporate a watermark concept to only pull data, make requests for new past data we don't have 

# Blocking
this issue blocks #3 #2

**Comment by littleforest** [comment]
@isometimescode and @zassmin:  finishing this up, and I wrote it to just do a `HEAD` request and compare the `etag` returned with a stored `etag` (if different, then pull the data).  However, the `head` request counts against our rate limiting values, so wondering if it just makes more sense to do the `GET` request, and if the `etag` hasn't changed then just return an empty hash; if it has changed return the data.  I haven't worked with the meetup api before - will we be retrieving huge responses where it would make sense to just do a `HEAD` first or will it likely be fairly negligible?

**Comment by isometimescode** [comment]
Well if additional HEAD requests count towards our rate limit, I think we'll have our scheduled tasks will take longer to complete/to get data, since we'll have to sleep more often. So I vote for just doing the GET request, maybe with the [`If-None-Match` Header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match)?

**Comment by littleforest** [comment]
sounds like a great solution, will implement that.
